# Run clang-format? (true/false)
run_clang_format: true
# Run clang-tidy? (true/false)
run_clang_tidy: true
# Whitelist of packages to run cmake_clang_tools.
# Empty list -> run on all packages.
whitelist: {}
# Blacklist of packages to not run cmake_clang_tools.
# Empty list -> ignore no packages.
blacklist: {}
